export const MockData = [
  {
    id: 1,
    name: 'Hamburguer',
    price: 10.0,
    description: 'Delicioso hamburguer com carne de primeira qualidade',
    category: 'Hamburguer',
  },
  {
    id: 2,
    name: 'Hotdog',
    price: 5.5,
    description: 'Hotdog com salsicha e pão fresquinho',
    category: 'Hotdog',
  },
  {
    id: 3,
    name: 'Guaraná Jesus',
    price: 3.2,
    description: 'Refrigerante geladinho',
    category: 'Bebida',
  },
  {
    id: 4,
    name: 'Pastel',
    price: 2.0,
    description: 'Pastel de carne ou queijo',
    category: 'Pastel',
  },
  {
    id: 5,
    name: 'Cheeseburguer',
    price: 12.0,
    description: 'Hamburguer com queijo derretido e molho especial',
    category: 'Hamburguer',
  },
  {
    id: 6,
    name: 'Hotdog Completo',
    price: 7.0,
    description: 'Hotdog com purê, milho, batata palha e queijo ralado',
    category: 'Hotdog',
  },
  {
    id: 7,
    name: 'Itubaína 2L',
    price: 10.0,
    description: 'Refrigerante para compartilhar, com 2 litros',
    category: 'Bebida',
  },
  {
    id: 8,
    name: 'Pastel de Frango',
    price: 2.5,
    description: 'Pastel recheado com frango temperado e desfiado',
    category: 'Pastel',
  },
  {
    id: 9,
    name: 'Hamburguer Duplo',
    price: 15.0,
    description: 'Hamburguer com duas carnes e queijo extra',
    category: 'Hamburguer',
  },
  {
    id: 10,
    name: 'Hotdog Simples',
    price: 4.0,
    description: 'Hotdog básico com pão e salsicha',
    category: 'Hotdog',
  },
  {
    id: 11,
    name: 'Coca-Cola Diet',
    price: 3.5,
    description: 'Refrigerante sem açúcar e geladinho',
    category: 'Bebida',
  },
  {
    id: 12,
    name: 'Pastel de Pizza',
    price: 3.0,
    description: 'Pastel recheado com queijo, presunto e orégano',
    category: 'Pastel',
  },
  {
    id: 13,
    name: 'X-Bacon',
    price: 14.0,
    description: 'Hamburguer com queijo, bacon crocante e molho especial',
    category: 'Hamburguer',
  },
  {
    id: 14,
    name: 'Hotdog com Catupiry',
    price: 6.0,
    description: 'Hotdog com uma camada generosa de catupiry',
    category: 'Hotdog',
  },
  {
    id: 15,
    name: 'Fanta Guaraná',
    price: 3.0,
    description: 'Refrigerante de guaraná gelado e refrescante',
    category: 'Bebida',
  },
  {
    id: 16,
    name: 'Pastel de Palmito',
    price: 3.5,
    description: 'Pastel recheado com palmito cremoso e temperado',
    category: 'Pastel',
  },
  {
    id: 17,
    name: 'X-Tudo',
    price: 18.0,
    description: 'Hamburguer completo com carne, queijo, bacon, ovo e salada',
    category: 'Hamburguer',
  },
  {
    id: 18,
    name: 'Hotdog Americano',
    price: 8.0,
    description: 'Hotdog com molho barbecue e cebola caramelizada',
    category: 'Hotdog',
  },
  {
    id: 19,
    name: 'Coca-Cola Zero',
    price: 3.8,
    description: 'Refrigerante zero açúcar com sabor original',
    category: 'Bebida',
  },
  {
    id: 20,
    name: 'Pastel de Calabresa',
    price: 3.5,
    description: 'Pastel recheado com calabresa picadinha e queijo',
    category: 'Pastel',
  },
];
